#Theme Selection
# remote_theme: pmarsceill/just-the-docs
remote_theme             : "mmistakes/minimal-mistakes@4.19.2"
minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"


title: "Installing Faveo"
description: "This website list down ways to install Faveo Helpdesk on different platforms"
search_enabled: true
lang: en

logo: "/assets/images/logo.png"
footer_content: "Copyright &copy; 2015-2020 Ladybird Web Solution Pvt Ltd."

# Permalink URLs structure, for permalink style options see: https://jekyllrb.com/docs/permalinks/
permalink:          /:title/

ga_tracking: UA-65420739-1


defaults:
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      sidebar:
        nav: "docs"
